2022-01-14 21:02:11.314 [error] <0.390.0> gen_server <0.390.0> terminated with reason: {socket_error,timeout}
2022-01-14 21:02:11.314 [error] <0.383.0> gen_server <0.383.0> terminated with reason: {socket_error,timeout}
2022-01-14 21:02:11.315 [error] <0.390.0> CRASH REPORT Process <0.390.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-14 21:02:11.315 [error] <0.382.0> Supervisor {<0.382.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.383.0>, <0.388.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:56586 -> 127.0.0.1:5672">>) at <0.390.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-14 21:02:11.315 [error] <0.382.0> Supervisor {<0.382.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8>, <0.383.0>, <0.388.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:56586 -> 127.0.0.1:5672">>) at <0.390.0> exit with reason reached_max_restart_intensity in context shutdown
2022-01-14 21:02:11.315 [error] <0.383.0> CRASH REPORT Process <0.383.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 811
2022-01-14 21:02:11.315 [error] <0.381.0> Supervisor {<0.381.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.382.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.383.0> exit with reason {socket_error,timeout} in context child_terminated
2022-01-14 21:02:11.315 [error] <0.381.0> Supervisor {<0.381.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.382.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.383.0> exit with reason reached_max_restart_intensity in context shutdown
